module.exports = {
  // AOI validation
  INVALID_AOI: "INVALID_AOI",
  AOI_TOO_SMALL: "AOI_TOO_SMALL",
  AOI_TOO_LARGE: "AOI_TOO_LARGE",
  INVALID_COORDINATES: "INVALID_COORDINATES",
  
  // Date validation
  INVALID_DATE: "INVALID_DATE",
  INVALID_DATE_RANGE: "INVALID_DATE_RANGE",
  DATE_IN_FUTURE: "DATE_IN_FUTURE",
  DATE_RANGE_TOO_LARGE: "DATE_RANGE_TOO_LARGE",
  DATE_TOO_OLD: "DATE_TOO_OLD",
  
  // Data availability
  NO_IMAGERY_AVAILABLE: "NO_IMAGERY_AVAILABLE",
  CLOUD_COVERAGE_HIGH: "CLOUD_COVERAGE_HIGH",
  
  // System errors
  MODEL_FAILURE: "MODEL_FAILURE",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NETWORK_ERROR: "NETWORK_ERROR",
  TIMEOUT_ERROR: "TIMEOUT_ERROR",
};
